### ISSUE TITLE
Schriftgrösse für Text unterschiedlich auf Landingpage

### ISSUE THREAD

**Issue by MartinaKessler** [ARpatterns/landingpage#20]
Die Schriftgrösse auf der Landingpage in der blau und grün markierten Box ist nicht gleich. Ich schlage vor, die Schriftgrösse in der blauen Box zu verkleinern.
![Screenshot 2024-10-11 at 15 15 47](https://github.com/user-attachments/assets/f67c4514-082e-43f5-aec4-64963662221d)

**Comment by haeslste** [comment]
Das wollte man so ;)
