### ISSUE TITLE
Github link to Illustrations

### ISSUE THREAD

**Issue by metason** [ARpatterns/landingpage#8]
find the same assets as SVG files in the download link below. -->
download the same assets as *SVG vector graphics*.

Mit link in ein neues Repo zu "illustration" containg the SVG files and/or the Illustrator template file.

**Comment by AlessandroHoller** [comment]
Habe alle Instanzen exportiert. Irgendwie habe ich keine Berechtigung, ins Repository hochzuladen. Daher hier der Link mit allen Einzeln-SVGs: 
[SVG Export 20.zip](https://github.com/user-attachments/files/17362750/SVG.Export.20.zip)
